server:
  port: 8081  # 서버 포트 설정

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

logging:
  level:
    root: INFO
    org.springframework.web.socket: DEBUG
    com.template: DEBUG

cors:
  allowed-origins: "*"
  allowed-methods: GET, POST
  allowed-headers: "*"


openai:
  key: #API-KEY
  stt:
    url: https://api.openai.com/v1/audio/transcriptions
  text-generator:
    url: https://api.openai.com/v1/chat/completions
    model: #text-generator-model