name: CI-CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Build Docker image
        run: docker build -t songhae/mallang-back:${{ github.sha }} .

      - name: Tag image as latest
        run: docker tag songhae/mallang-back:${{ github.sha }} songhae/mallang-back:latest

      - name: Log into Docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image (commit SHA)
        run: docker push songhae/mallang-back:${{ github.sha }}

      - name: Push Docker image (latest)
        run: docker push songhae/mallang-back:latest

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/ubuntu/mallang
            docker pull songhae/mallang-back:latest
            docker stop mallang-back || true
            docker rm mallang-back || true
            docker run -d -p 8081:8081 --name mallang-back -e OPENAI_KEY=${{secrets.OPENAI_KEY}}  -e TEXT_GENERATOR_MODEL=gpt-3.5-turbo songhae/mallang-back 
            docker image prune -af

      - name: Health Check
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "== Health check 시작 =="
            start_time=$(date +%s)
            for i in {1..300}
            do
              response=$(curl -s http://localhost:8081/actuator/health || true)
              if echo "$response" | grep -q "\"UP\""; then
                end_time=$(date +%s)
                duration=$(( end_time - start_time ))
                echo "서버 기동이 확인되었습니다!"
                echo "총 소요 시간: ${duration}초"
                exit 0
              fi
            
              # 10초마다 진행 중 메시지 출력
              if [ $(( i % 10 )) -eq 0 ]; then
                echo "서버가 아직 기동되지 않았습니다. (${i}초 경과) 계속 헬스 체크 중..."
              fi
            
              sleep 1
            done
            echo "서버가 정상 기동되지 않았습니다. 스크립트를 종료합니다."
            exit 1